from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow24(object):
    def ekle(self):
        veri = self.listWidget.currentRow()
        bilgi = self.listWidget.takeItem(veri)
        self.listWidget_2.addItem(bilgi)

    def sil(self):
        veri = self.listWidget_2.currentRow()
        bilgi = self.listWidget_2.takeItem(veri)
        self.listWidget.addItem(bilgi)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 20, 481, 231))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 230, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.ekle)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 280, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.sil)


        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(40, 310, 481, 281))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 280, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DERS EKLE-SİL"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Ders Adı                      AKTS                 Dönem              Durum"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Edebiyat                         2                    2022-2023            Zorunlu"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Matematik                      2                    2022-2023            Zorunlu"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Görsel Prog.                   5                     2022-2023           Zorunlu"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Veritabanı ||                   5                     2022-2023           Zorunlu"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "Nesne Taban.                 3                     2022-2023           Zorunlu"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Çevre Koruma                3                    2022-2023            Seçmeli"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "İş Sağlığı                        3                    2022-2023            Seçmeli"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "Medya Okur.                  2                    2022-2023             Seçmeli"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "Kalite Güvence              2                    2022-2023             Seçmeli"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "EKLE"))
        self.pushButton_2.setText(_translate("MainWindow", "SİL"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "Ders Adı                      AKTS                 Dönem              Durum"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "DERSLERİM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow24()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
