from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow28(object):
    def nakil(self):
        self.label_2.setText("Nakil başvurunuz gönderildi.")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 550)
        MainWindow.setMaximumSize(QtCore.QSize(950, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(270, 240, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 250, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")


        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(270, 300, 171, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 310, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 400, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.nakil)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 370, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 691, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 681, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 460, 771, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NAKİL"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Adana"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Adıyaman"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Afyonkarahisar"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Ağrı"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Amasya"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Ankara"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Antalya"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Artvin"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Aydın"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Balıkesir"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Bursa"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Çanakkale"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Denizli"))
        self.comboBox.setItemText(13, _translate("MainWindow", "İstanbul"))
        self.label.setText(_translate("MainWindow", "İL:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Anadolu Üniversitesi"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Pamukkale Üniversitesi"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Boğaziçi Üniversitesi"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "İTÜ"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Bahçeşehir Üniversitesi"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "ODTÜ"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Cerrahpaşa Üniversiteisi"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "KTÜ"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9 Eylül Üniversitesi"))
        self.label_3.setText(_translate("MainWindow", "OKUL:"))
        self.pushButton.setText(_translate("MainWindow", "GÖNDER"))
        self.label_2.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "Kadrolu personelin isteğe bağlı nakil çalışmasına ilişkin ilke kararları, bölgelere ilişkin puan tablosu, tüm"))
        self.label_5.setText(_translate("MainWindow", "  adliyelerin puanlarını gösterir tablo ve başvuru kılavuzu ektedir."))
        self.label_6.setText(_translate("MainWindow", "UYAP Personel Merkezi Nakil Sistemi ile ilgili 0 312 414 63 09 nolu telefon numaralarından yardım alınabilecektir."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow28()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
