from PyQt5 import QtCore, QtGui, QtWidgets
from ogrenci_girisi2 import Ui_MainWindow22
from personel_girisi_python import Ui_MainWindow3

class Ui_MainWindow(object):
    def yeni(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow22()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    def yeni2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow3()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1128, 789)
        MainWindow.setMaximumSize(QtCore.QSize(1128, 822))
        MainWindow.setStyleSheet("background-color: rgb(56, 103, 190);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1131, 91))
        self.label.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(60, 260, 421, 321))
        self.listWidget.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.listWidget.addItem(item)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Onyx")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 20pt \"Onyx\";")
        self.label_2.setObjectName("label_2")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 291, 51))
        self.label_4.setStyleSheet("font: 13pt \"Eras Bold ITC\";\n"
"background-color: rgb(56, 103, 190);")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 310, 151, 71))
        self.pushButton_2.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.yeni)


        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(770, 420, 151, 71))
        self.pushButton_3.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton_3.clicked.connect(self.yeni2)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OTOMASYON SİSTEMİ"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Yeni kayıtlar başladı."))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Ders ekle-sil günleri belli oldu."))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Akademik takvim açıklandı."))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "Erasmus başvuruları başladı."))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "Festival takvimleri belli oldu."))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "Personel alımları başladı."))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "                           DUYURULAR                                               "))
        self.label_4.setText(_translate("MainWindow", "         AKIL OKULLARI"))
        self.pushButton_2.setText(_translate("MainWindow", "Öğrenci Girişi"))
        self.pushButton_3.setText(_translate("MainWindow", "Personel Girişi"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
